### ISSUE TITLE
 tt.normalise_trajectories(t, body_length) : Too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by matiasandina** [fjhheras/trajectorytools#1]
I'm following the notebook on Gitlab (T0_loading_idtrackerai_trajectories.ipynb)
It calls for 

```
tt.Trajectories.from_positions(trajectories)
```

But it returns the error regarding `normalise_trajectories`

I noticed that `trajectories.py` contains

```
        if interpolate_nans:
            tt.interpolate_nans(t)
        radius, center_x, center_y = \
            tt.normalise_trajectories(t, body_length)
```
Meaning, it's expecting 3 values `radius, center_x, center_y`. However, the output from `normalise_trajectories` looks like:

```
    if body_length is not None:
        np.divide(t, body_length, t)
        return radius/body_length, center_x/body_length, center_y/body_length, body_length
    else:
        np.divide(t, radius, t)
        return 1, center_x/radius, center_y/radius, radius
```

Thus giving 4 values back. Interestingly, if I just ran `normalise_trajectories` , I get an output that seems to make sense.

```
tt.normalise_trajectories(trajectories.copy(), body_length=body_length)
(0.007518796992481203, 2.439047293290699e-18, 0.0, 133)
```
Should we modify the call within `trajectories` to include `body_length` as expected output?

**Comment by fjhheras** [comment]
Hi!

Thank you for noticing. We made a hotfix branch called hotfix_inconsistentnormalisation
Could you please confirm that your issue dissapears when using that branch?

**Comment by matiasandina** [comment]
So I was able to go through by adding `radius, center_x, center_y, body_length = \ ...` *and* with the hotfix. Both methods seem to produce the same results, not sure what the differences are because I havn't studied the code long enough yet.

**Comment by fjhheras** [comment]
Cool. I will close the issue and merge to master.
