### ISSUE TITLE
.from_idtrackerai fails when "setup_points" value is None

### ISSUE THREAD

**Issue by DeanTM** [fjhheras/trajectorytools#39]
For some reason `traj_dict["setup_points"]` can be `None`, so that the first if-clause passes but the second raises an error.

https://github.com/fjhheras/trajectorytools/blob/7640b6ed241ed82e9ab7d635f5698bba6e74ef25/trajectorytools/trajectories.py#L47

Perhaps defining `traj_dict["setup_points"] = {}` earlier in the code, or deleting `traj_dict["setup_points"]` if it's value is `None`, would avoid this problem.

**Comment by fjhheras** [comment]
Solved with pull request #40
